# =========================================================================
#  Builds the pgfplots data blocks used by slides_IIFET.tex from the
#  scenario CSVs written by
#  code/R/estimation/main/scenario_dynamic_same_months_percluster.R
#
#  Run from anywhere:  Rscript slides/make_scenario_figdata.R
#  Writes:             slides/data/scenario_species.tex
#                      slides/data/scenario_participation.tex
#
#  Base R only -- no tidyverse, so it runs on a bare R install.
# =========================================================================

# Resolve the paper directory robustly whether run via Rscript or source().
args <- commandArgs(trailingOnly = FALSE)
script_path <- sub("^--file=", "", args[grep("^--file=", args)])
if (length(script_path) == 1) {
  slides_dir <- dirname(normalizePath(script_path))
} else {
  slides_dir <- normalizePath(".")
}
part_dir <- normalizePath(file.path(slides_dir, ".."))
scen_dir <- file.path(part_dir, "Results", "r_output", "scenarios")
out_dir  <- file.path(slides_dir, "data")
dir.create(out_dir, showWarnings = FALSE, recursive = TRUE)

sp_csv   <- file.path(scen_dir, "scenario_dynamic_same_months_delta_species_pp.csv")
part_csv <- file.path(scen_dir, "scenario_dynamic_same_months_delta_participation_pp.csv")
port_csv <- file.path(scen_dir, "scenario_dynamic_same_months_delta_port_pp.csv")
stopifnot(file.exists(sp_csv), file.exists(part_csv), file.exists(port_csv))

spec_labels <- c(
  PSDN = "Pacific sardine", NANC = "Northern anchovy", MSQD = "Market squid",
  CMCK = "Chub mackerel",   JMCK = "Jack mackerel",    YTNA = "Yellowfin tuna",
  BTNA = "Bluefin tuna",    DCRB = "Dungeness crab",   ALBC = "Albacore",
  SOCK = "Sockeye"
)

# Shortened from the paper's port_labels -- the full names ("Coastal Washington
# Ports", "Columbia River (Washington)") do not fit a small-multiple panel.
port_labels <- c(
  laa = "Los Angeles",   sfa = "San Francisco", mna = "Monterey",
  sba = "Santa Barbara", mra = "Morro Bay",     cwa = "Coastal WA",
  clo = "Columbia R.~(OR)", clw = "Columbia R.~(WA)", cba = "Coos Bay",
  nps = "N.~Puget Sound",   npa = "Newport",     sda = "San Diego"
)

# Short panel titles -- the full cluster names do not fit a 2x2 panel header.
seg_short <- c(
  c4 = "S.\\ CCS squid specialist",
  c5 = "Roving squid--sardine",
  c6 = "PNW sardine specialist",
  c7 = "S.\\ CCS forage diverse"
)

# TeX control words are letters only, so \SegPosC4 would parse as \SegPosC
# delimited by "4". Suffix the macros with spelled-out digits instead.
tex_suffix <- c(c4 = "Cfour", c5 = "Cfive", c6 = "Csix", c7 = "Cseven")

# pgfplots "coordinates {(x,y) [label]}" with explicit symbolic point meta.
# `flip` swaps the axes for the vertical-bar chart.
coord_labels <- function(values, positions, keep, flip = FALSE) {
  if (!any(keep)) return("")
  v <- values[keep]; p <- positions[keep]
  paste(sprintf(if (flip) "(%d,%.3f) [%+.1f]" else "(%.3f,%d) [%+.2f]",
                if (flip) p else v, if (flip) v else p, v),
        collapse = " ")
}

# Emits one 2x2 small-multiple block: five largest |delta| per fleet segment,
# `prefix` keeps the species and port blocks from colliding in the macro
# namespace. `min_label` is the smallest bar that still gets a printed value.
write_panels <- function(df, dict, prefix, outfile, source_csv, min_label = 0.3,
                         lowercase_keys = FALSE) {
  out <- c(
    "% ---------------------------------------------------------------------",
    "% GENERATED by slides/make_scenario_figdata.R -- do not edit by hand.",
    "% Source: Results/r_output/scenarios/",
    paste0("%         ", source_csv),
    "% ---------------------------------------------------------------------"
  )
  for (cl in c("c4", "c5", "c6", "c7")) {
    d <- df[df$cluster == cl, ]
    d <- d[order(abs(d$delta_pp), decreasing = TRUE), ]
    d <- head(d, 5)
    d <- d[order(abs(d$delta_pp)), ]        # smallest at bottom -> plots upward
    key <- if (lowercase_keys) tolower(d$group) else d$group
    labs <- ifelse(key %in% names(dict), dict[key], d$group)
    pos  <- seq_along(labs) - 1L
    sfx  <- paste0(prefix, tex_suffix[[cl]])
    keep <- abs(d$delta_pp) >= min_label

    out <- c(out, "",
      sprintf("\\def\\%sTitle%s{%s}", prefix, tex_suffix[[cl]], seg_short[[cl]]),
      sprintf("\\def\\%sTicks%s{%s}", prefix, tex_suffix[[cl]],
              paste(pos, collapse = ",")),
      sprintf("\\def\\%sLabels%s{%s}", prefix, tex_suffix[[cl]],
              paste(labs, collapse = ",")),
      sprintf("\\def\\%sPos%s{%s}", prefix, tex_suffix[[cl]],
              paste(sprintf("(%.3f,%d)", pmax(d$delta_pp, 0), pos), collapse = " ")),
      sprintf("\\def\\%sNeg%s{%s}", prefix, tex_suffix[[cl]],
              paste(sprintf("(%.3f,%d)", pmin(d$delta_pp, 0), pos), collapse = " ")),
      # Value labels ride along as explicit symbolic point meta, so pgfplots
      # prints exactly this string. Positive and negative are separate plots so
      # each can carry its own anchor.
      sprintf("\\def\\%sLabPos%s{%s}", prefix, tex_suffix[[cl]],
              coord_labels(d$delta_pp, pos, keep & d$delta_pp >= 0)),
      sprintf("\\def\\%sLabNeg%s{%s}", prefix, tex_suffix[[cl]],
              coord_labels(d$delta_pp, pos, keep & d$delta_pp < 0))
    )
    stopifnot(nzchar(sfx))
  }
  writeLines(out, file.path(out_dir, outfile))
}

write_panels(read.csv(sp_csv, stringsAsFactors = FALSE), spec_labels, "Seg",
             "scenario_species.tex",
             "scenario_dynamic_same_months_delta_species_pp.csv")

# Ports: the spatial reallocation -- which landing ports gain and lose effort.
write_panels(read.csv(port_csv, stringsAsFactors = FALSE), port_labels, "Prt",
             "scenario_port.tex",
             "scenario_dynamic_same_months_delta_port_pp.csv",
             min_label = 0.5, lowercase_keys = TRUE)

# ---- participation -------------------------------------------------------
pa <- read.csv(part_csv, stringsAsFactors = FALSE)
pa$cluster <- as.character(pa$cluster)
pa <- pa[match(c("c4", "c5", "c6", "c7"), pa$cluster), ]

plines <- c(
  "% ---------------------------------------------------------------------",
  "% GENERATED by slides/make_scenario_figdata.R -- do not edit by hand.",
  "% Source: Results/r_output/scenarios/",
  "%         scenario_dynamic_same_months_delta_participation_pp.csv",
  "% delta_pp = change in P(participate) = -change in P(no participation).",
  "% ---------------------------------------------------------------------",
  "",
  sprintf("\\def\\PartLabels{%s}",
          paste(seg_short[pa$cluster], collapse = ",")),
  sprintf("\\def\\PartPos{%s}",
          paste(sprintf("(%d,%.3f)", seq_len(nrow(pa)) - 1, pmax(pa$delta_pp, 0)),
                collapse = " ")),
  sprintf("\\def\\PartNeg{%s}",
          paste(sprintf("(%d,%.3f)", seq_len(nrow(pa)) - 1, pmin(pa$delta_pp, 0)),
                collapse = " ")),
  sprintf("\\def\\PartLabPos{%s}",
          coord_labels(pa$delta_pp, seq_len(nrow(pa)) - 1L, pa$delta_pp >= 0,
                       flip = TRUE)),
  sprintf("\\def\\PartLabNeg{%s}",
          coord_labels(pa$delta_pp, seq_len(nrow(pa)) - 1L, pa$delta_pp < 0,
                       flip = TRUE))
)

writeLines(plines, file.path(out_dir, "scenario_participation.tex"))

cat("Wrote:\n  ", file.path(out_dir, "scenario_species.tex"), "\n  ",
    file.path(out_dir, "scenario_participation.tex"), "\n", sep = "")
