

gc()
rm(list = ls())
library(data.tree)

# vessel <- Node$new("Vessel")
#   part <- vessel$AddChild("Participate")
#     laa <- part$AddChild("LA")
#       cps <- laa$AddChild("CPS")      
#         cmck <- cps$AddChild("Mackerel")
#         msqd <- cps$AddChild("Squid")
#         nanc <- cps$AddChild("Anchovy")
#         psdn <- cps$AddChild("Sardine")
#       tuna <- laa$AddChild("Tuna")      
#         ytna <- tuna$AddChild("Yellowfin")
#     mna <- part$AddChild("Monterey")
#       msqd <- mna$AddChild("Squid")
#       nanc <- mna$AddChild("Anchovy")
#       psdn <- mna$AddChild("Sardine")
#     mra <- part$AddChild("Morrobay")
#       msqd <- mra$AddChild("Squid")
#     sba <- part$AddChild("Santa Barbara")
#       cmck <- sba$AddChild("Mackerel")
#       msqd <- sba$AddChild("Squid")
#     sfa <- part$AddChild("San Francisco")
#       msqd <- sfa$AddChild("Squid")
#       nanc <- sfa$AddChild("Anchovy")
#   nopart <- vessel$AddChild("No participate")
# 
# SetGraphStyle(vessel, rankdir = "TB")
# SetEdgeStyle(vessel, arrowhead = "vee", color = "grey35", penwidth = 2)
# SetNodeStyle(vessel, style = "filled,rounded", shape = "box", fillcolor = "DarkGreen", 
#              fontname = "helvetica", tooltip = GetDefaultTooltip)
# SetNodeStyle(vessel$`No participate`, fillcolor = "Firebrick")
# SetNodeStyle(laa$Tuna, fillcolor = "Blue")
# plot(vessel)
#   

vessel2 <- Node$new("Vessel")
  part <- vessel2$AddChild("Participate in CPS or Tuna")
    msqd <- part$AddChild("Squid")
      laa <- msqd$AddChild("Los\nAngeles")
      mna <- msqd$AddChild("Monterey")
      mra <- msqd$AddChild("Morrobay")
      sba <- msqd$AddChild("Santa\nBarbara")
      sfa <- msqd$AddChild("San\nFrancisco")
      cba <- msqd$AddChild("Coos Bay")
      npa <- msqd$AddChild("Newport")
    cmck <- part$AddChild("Mackerel")
      laa <- cmck$AddChild("Los\nAngeles")
      sba <- cmck$AddChild("Santa\nBarbara")
    nanc <- part$AddChild("Anchovy")
      laa <- nanc$AddChild("Los\nAngeles")
    psdn <- part$AddChild("Sardine")
      clo <- psdn$AddChild("Columbia\nRiver (OR)")
      cwa <- psdn$AddChild("Coastal WA")
      clw <- psdn$AddChild("Columbia\nRiver (WA)")
      laa <- psdn$AddChild("Los\nAngeles")
    tuna <- part$AddChild("Albacore")
      cwa <- tuna$AddChild("Coastal WA")
  part_dcrb <- vessel2$AddChild("Participate in Crab")
    dcrb <- part_dcrb$AddChild("Dungeness\nCrab")
    clw <- dcrb$AddChild("Columbia\nRiver (WA)")
    cwa <- dcrb$AddChild("Coastal WA")
  nopart <- vessel2$AddChild("No\nparticipate")
  
SetGraphStyle(vessel2, rankdir = "TB")
SetEdgeStyle(vessel2, arrowhead = "vee", color = "grey35", penwidth = 2)
SetNodeStyle(vessel2, style = "filled,rounded", shape = "box", fontcolor = "black",fillcolor = "lightgrey", 
             fontname = "helvetica", tooltip = GetDefaultTooltip)
SetNodeStyle(vessel2$`No\nparticipate`, fillcolor = "firebrick1")
SetNodeStyle(vessel2$`Participate in CPS or Tuna`, fillcolor = "ivory1")
SetNodeStyle(vessel2$`Participate in CPS or Tuna`$Albacore, fillcolor = "powderblue")
SetNodeStyle(vessel2$`Participate in Crab` , fillcolor = "powderblue")
plot(vessel2)

