gc()
library(data.tree)

vessel <- Node$new("Vessel")
  part <- vessel$AddChild("Participate")
    laa <- part$AddChild("LA")
      cps <- laa$AddChild("CPS")      
        cmck <- cps$AddChild("Mackerel")
        msqd <- cps$AddChild("Squid")
        nanc <- cps$AddChild("Anchovy")
        psdn <- cps$AddChild("Sardine")
      tuna <- laa$AddChild("Tuna")      
        ytna <- tuna$AddChild("Yellowfin")
    mna <- part$AddChild("Monterey")
      msqd <- mna$AddChild("Squid")
      nanc <- mna$AddChild("Anchovy")
      psdn <- mna$AddChild("Sardine")
    mra <- part$AddChild("Morrobay")
      msqd <- mra$AddChild("Squid")
    sba <- part$AddChild("Santa Barbara")
      cmck <- sba$AddChild("Mackerel")
      msqd <- sba$AddChild("Squid")
    sfa <- part$AddChild("San Francisco")
      msqd <- sfa$AddChild("Squid")
      nanc <- sfa$AddChild("Anchovy")
  nopart <- vessel$AddChild("No participate")

SetGraphStyle(vessel, rankdir = "TB")
SetEdgeStyle(vessel, arrowhead = "vee", color = "grey35", penwidth = 2)
SetNodeStyle(vessel, style = "filled,rounded", shape = "box", fillcolor = "DarkGreen", 
             fontname = "helvetica", tooltip = GetDefaultTooltip)
SetNodeStyle(vessel$`No participate`, fillcolor = "Firebrick")
SetNodeStyle(laa$Tuna, fillcolor = "Blue")
plot(vessel)
  

plot(vessel)


vessel2 <- Node$new("Vessel")
  part <- vessel2$AddChild("Participate")
    msqd <- part$AddChild("Squid")
      laa <- msqd$AddChild("LA")
      mna <- msqd$AddChild("Monterey")
      mra <- msqd$AddChild("Morrobay")
      sba <- msqd$AddChild("Santa Barbara")
      sfa <- msqd$AddChild("San Francisco")
    cmck <- part$AddChild("Mackerel")
      laa <- cmck$AddChild("LA")
      sba <- cmck$AddChild("Santa Barbara")
    nanc <- part$AddChild("Anchovy")
      laa <- nanc$AddChild("LA")
      mna <- nanc$AddChild("Monterey")
      sfa <- nanc$AddChild("San Francisco")
    psdn <- part$AddChild("Sardine")
      laa <- psdn$AddChild("LA")
      mna <- psdn$AddChild("Monterey")
    ytna <- part$AddChild("Yellowfin")
      laa <- ytna$AddChild("LA")
  nopart <- vessel2$AddChild("No participate")
  
SetGraphStyle(vessel2, rankdir = "TB")
SetEdgeStyle(vessel2, arrowhead = "vee", color = "grey35", penwidth = 2)
SetNodeStyle(vessel2, style = "filled,rounded", shape = "box", fillcolor = "DarkGreen", 
             fontname = "helvetica", tooltip = GetDefaultTooltip)
SetNodeStyle(vessel2$`No participate`, fillcolor = "Firebrick")
SetNodeStyle(vessel2$Participate$Yellowfin, fillcolor = "Blue")
plot(vessel2)

