

gc()
rm(list = ls())
library(data.tree)

# vessel <- Node$new("Vessel")
#   part <- vessel$AddChild("Participate")
#     laa <- part$AddChild("LA")
#       cps <- laa$AddChild("CPS")      
#         cmck <- cps$AddChild("Mackerel")
#         msqd <- cps$AddChild("Squid")
#         nanc <- cps$AddChild("Anchovy")
#         psdn <- cps$AddChild("Sardine")
#       tuna <- laa$AddChild("Tuna")      
#         ytna <- tuna$AddChild("Yellowfin")
#     mna <- part$AddChild("Monterey")
#       msqd <- mna$AddChild("Squid")
#       nanc <- mna$AddChild("Anchovy")
#       psdn <- mna$AddChild("Sardine")
#     mra <- part$AddChild("Morrobay")
#       msqd <- mra$AddChild("Squid")
#     sba <- part$AddChild("Santa Barbara")
#       cmck <- sba$AddChild("Mackerel")
#       msqd <- sba$AddChild("Squid")
#     sfa <- part$AddChild("San Francisco")
#       msqd <- sfa$AddChild("Squid")
#       nanc <- sfa$AddChild("Anchovy")
#   nopart <- vessel$AddChild("No participate")
# 
# SetGraphStyle(vessel, rankdir = "TB")
# SetEdgeStyle(vessel, arrowhead = "vee", color = "grey35", penwidth = 2)
# SetNodeStyle(vessel, style = "filled,rounded", shape = "box", fillcolor = "DarkGreen", 
#              fontname = "helvetica", tooltip = GetDefaultTooltip)
# SetNodeStyle(vessel$`No participate`, fillcolor = "Firebrick")
# SetNodeStyle(laa$Tuna, fillcolor = "Blue")
# plot(vessel)
#   

vessel2 <- Node$new("Vessel")
  part <- vessel2$AddChild("Participate")
    msqd <- part$AddChild("Squid")
      laa <- msqd$AddChild("Los\nAngeles")
      mna <- msqd$AddChild("Monterey")
      mra <- msqd$AddChild("Morro Bay")
      sba <- msqd$AddChild("Santa\nBarbara")
      sfa <- msqd$AddChild("San\nFrancisco")
    cmck <- part$AddChild("Mackerel")
      laa <- cmck$AddChild("Los\nAngeles")
      sba <- cmck$AddChild("Santa\nBarbara")
    nanc <- part$AddChild("Anchovy")
      laa <- nanc$AddChild("Los\nAngeles")
      mna <- nanc$AddChild("Monterey")
      sfa <- nanc$AddChild("San\nFrancisco")
    psdn <- part$AddChild("Sardine")
      laa <- psdn$AddChild("Los\nAngeles")
      mna <- psdn$AddChild("Monterey")
    tuna <- part$AddChild("Tuna")
      ytna <- tuna$AddChild("Yellowfin")
      btna <- tuna$AddChild("Bluefin")
  nopart <- vessel2$AddChild("No\nparticipation")
  
SetGraphStyle(vessel2, rankdir = "LR")
SetEdgeStyle(vessel2, arrowhead = "vee", color = "grey35", penwidth = 2)
SetNodeStyle(vessel2, style = "filled,rounded", shape = "box", fontcolor = "black",fillcolor = "lightgrey", 
             fontname = "helvetica", tooltip = GetDefaultTooltip)
SetNodeStyle(vessel2$`No\nparticipation`, fillcolor = "firebrick1")
SetNodeStyle(vessel2$Participate, fillcolor = "ivory1")
SetNodeStyle(vessel2$Participate$Tuna, fillcolor = "powderblue")
plot(vessel2)

